# UAS Statkom

### Import library

In [ ]:
import pandas as pd

# Baca data

In [2]:
dataFrame = pd.read_excel('Data_Mahasiswa.xlsx')
dataFrame

    JENIS KELAMIN     ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
0       Perempuan      Luar Pulau  Tidak      SMA  Sudah  Karyawan  Terlambat
1       Laki-laki      Luar Pulau  Tidak      SMA  Belum  Karyawan      Tepat
2       Perempuan  Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
3       Laki-laki      Luar Pulau     Ya       MA  Belum   Reguler  Terlambat
4       Perempuan  Dalam Provinsi  Tidak      SMK  Sudah   Reguler      Tepat
..            ...             ...    ...      ...    ...       ...        ...
139     Perempuan  Dalam Provinsi     Ya      SMK  Belum  Karyawan      Tepat
140     Laki-laki      Luar Pulau     Ya       MA  Belum  Karyawan  Terlambat
141     Perempuan  Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat
142     Laki-laki  Dalam Provinsi     Ya      SMA  Sudah  Karyawan      Tepat
143     Perempuan  Dalam Provinsi  Tidak       MA  Belum  Karyawan      Tepat

[144 rows x 7 columns]

Mengambil data kolom

In [3]:
jenisKelamin = dataFrame['JENIS KELAMIN']
asalDaerah = dataFrame['ASAL DAERAH']
cuti = dataFrame['CUTI']
asalSMA = dataFrame['ASAL SMA']
nikah = dataFrame['NIKAH']
program = dataFrame['PROGRAM']
kelas = dataFrame['KELAS']

# Distribusi data
Memisahkan data menjadi data training dan data testing dengan perbandingan 80:20

#### Data kelas "Tepat"

In [4]:
kelas_tepat = dataFrame[kelas == 'Tepat']
print(len(kelas_tepat))
kelas_tepat

80

    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM  KELAS
1       Laki-laki       Luar Pulau  Tidak      SMA  Belum  Karyawan  Tepat
4       Perempuan   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
5       Laki-laki  Dalam Kabupaten  Tidak      SMK  Sudah   Reguler  Tepat
6       Laki-laki       Luar Pulau  Tidak      SMK  Sudah   Reguler  Tepat
7       Perempuan       Luar Pulau  Tidak      SMA  Belum   Reguler  Tepat
..            ...              ...    ...      ...    ...       ...    ...
134     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler  Tepat
136     Perempuan   Dalam Provinsi     Ya       MA  Belum   Reguler  Tepat
139     Perempuan   Dalam Provinsi     Ya      SMK  Belum  Karyawan  Tepat
142     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Tepat
143     Perempuan   Dalam Provinsi  Tidak       MA  Belum  Karyawan  Tepat

[80 rows x 7 columns]

Memisahkan 70% data dari kelas yang bernilai "Tepat" sebagai data training. 30% sisanya akan menjadi data testing.

In [5]:
# Menenentukan index ke berapa data akan dipotong
index_potong_tepat = int(len(kelas_tepat) * 0.7)
index_potong_tepat

56

In [6]:
data_training_tepat = kelas_tepat.iloc[:index_potong_tepat]
data_testing_tepat = kelas_tepat.iloc[index_potong_tepat:]
print(len(data_training_tepat))
print(len(data_testing_tepat))
print(data_training_tepat)
print()
print(data_testing_tepat)

56
24
   JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM  KELAS
1      Laki-laki       Luar Pulau  Tidak      SMA  Belum  Karyawan  Tepat
4      Perempuan   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
5      Laki-laki  Dalam Kabupaten  Tidak      SMK  Sudah   Reguler  Tepat
6      Laki-laki       Luar Pulau  Tidak      SMK  Sudah   Reguler  Tepat
7      Perempuan       Luar Pulau  Tidak      SMA  Belum   Reguler  Tepat
9      Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
13     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler  Tepat
15     Laki-laki   Dalam Provinsi     Ya      SMA  Belum   Reguler  Tepat
16     Perempuan  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Tepat
19     Perempuan   Dalam Provinsi     Ya       MA  Belum  Karyawan  Tepat
20     Perempuan       Luar Pulau  Tidak      SMA  Sudah   Reguler  Tepat
21     Perempuan  Dalam Kabupaten  Tidak      SMK  Belum   Reguler  Tepat
24     Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
25     Laki-laki       Luar Pulau     Ya      SMA  Belum   Reguler  Tepat
28     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan  Tepat
29     Laki-laki       Luar Pulau  Tidak       MA  Belum   Reguler  Tepat
32     Perempuan  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Tepat
33     Laki-laki   Dalam Provinsi  Tidak       MA  Sudah   Reguler  Tepat
34     Perempuan  Dalam Kabupaten  Tidak      SMA  Belum   Reguler  Tepat
35     Laki-laki       Luar Pulau  Tidak       MA  Sudah  Karyawan  Tepat
38     Perempuan       Luar Pulau     Ya      SMA  Belum   Reguler  Tepat
39     Laki-laki   Dalam Provinsi  Tidak      SMK  Belum  Karyawan  Tepat
40     Laki-laki  Dalam Kabupaten  Tidak       MA  Belum   Reguler  Tepat
41     Laki-laki  Dalam Kabupaten     Ya      SMA  Belum   Reguler  Tepat
43     Laki-laki       Luar Pulau  Tidak      SMK  Belum   Reguler  Tepat
44     Laki-laki  Dalam Kabupaten  Tidak      SMK  Belum   Reguler  Tepat
45     Perempuan  Dalam Kabupaten     Ya      SMK  Belum   Reguler  Tepat
47     Laki-laki   Dalam Provinsi     Ya      SMK  Belum  Karyawan  Tepat
48     Perempuan   Dalam Provinsi  Tidak       MA  Belum   Reguler  Tepat
50     Laki-laki       Luar Pulau  Tidak      SMK  Sudah   Reguler  Tepat
51     Laki-laki  Dalam Kabupaten     Ya      SMA  Belum   Reguler  Tepat
54     Perempuan  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan  Tepat
56     Perempuan       Luar Pulau  Tidak       MA  Belum   Reguler  Tepat
57     Laki-laki       Luar Pulau  Tidak      SMK  Belum  Karyawan  Tepat
58     Perempuan       Luar Pulau  Tidak      SMK  Sudah  Karyawan  Tepat
59     Perempuan   Dalam Provinsi     Ya      SMA  Belum   Reguler  Tepat
60     Laki-laki       Luar Pulau  Tidak       MA  Sudah  Karyawan  Tepat
61     Laki-laki       Luar Pulau  Tidak      SMA  Belum  Karyawan  Tepat
62     Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
65     Perempuan  Dalam Kabupaten     Ya      SMA  Belum  Karyawan  Tepat
67     Laki-laki       Luar Pulau  Tidak       MA  Sudah  Karyawan  Tepat
68     Perempuan       Luar Pulau  Tidak      SMA  Belum  Karyawan  Tepat
69     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum   Reguler  Tepat
72     Perempuan  Dalam Kabupaten  Tidak       MA  Belum  Karyawan  Tepat
73     Laki-laki       Luar Pulau  Tidak      SMA  Sudah  Karyawan  Tepat
75     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah   Reguler  Tepat
77     Laki-laki  Dalam Kabupaten  Tidak      SMA  Belum  Karyawan  Tepat
78     Laki-laki  Dalam Kabupaten  Tidak      SMK  Sudah  Karyawan  Tepat
79     Perempuan  Dalam Kabupaten  Tidak       MA  Belum  Karyawan  Tepat
80     Perempuan  Dalam Kabupaten  Tidak       MA  Belum  Karyawan  Tepat
83     Laki-laki   Dalam Provinsi     Ya      SMK  Sudah  Karyawan  Tepat
84     Perempuan  Dalam Kabupaten  Tidak      SMK  Sudah  Karyawan  Tepat
85     Laki-laki       Luar Pulau  Tidak      SMK  Belum  Karyawan  Tepat
87     Perempuan  Dalam Kabupaten  Tidak       MA  Belum  Karyawan  Tepat
88     Perempuan  Dalam Kabupaten  Tidak       MA  Belum   Reguler  Tepat
94     Laki-laki  Dalam Kabupaten  Tidak       MA  Belum  Karyawan  Tepat

    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM  KELAS
96      Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Tepat
97      Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler  Tepat
99      Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan  Tepat
100     Perempuan       Luar Pulau     Ya      SMA  Belum  Karyawan  Tepat
102     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan  Tepat
104     Perempuan       Luar Pulau  Tidak      SMA  Belum   Reguler  Tepat
106     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler  Tepat
109     Perempuan       Luar Pulau  Tidak       MA  Belum  Karyawan  Tepat
111     Laki-laki       Luar Pulau     Ya      SMK  Belum   Reguler  Tepat
113     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Tepat
115     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler  Tepat
116     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Tepat
120     Perempuan  Dalam Kabupaten  Tidak       MA  Belum   Reguler  Tepat
121     Perempuan       Luar Pulau  Tidak      SMA  Belum  Karyawan  Tepat
122     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler  Tepat
126     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan  Tepat
130     Laki-laki  Dalam Kabupaten  Tidak      SMA  Sudah  Karyawan  Tepat
131     Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler  Tepat
132     Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan  Tepat
134     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler  Tepat
136     Perempuan   Dalam Provinsi     Ya       MA  Belum   Reguler  Tepat
139     Perempuan   Dalam Provinsi     Ya      SMK  Belum  Karyawan  Tepat
142     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Tepat
143     Perempuan   Dalam Provinsi  Tidak       MA  Belum  Karyawan  Tepat

#### Data kelas "Terlambat"

In [7]:
kelas_terlambat = dataFrame[kelas == 'Terlambat']
print(len(kelas_terlambat))
kelas_terlambat

64

    JENIS KELAMIN     ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
0       Perempuan      Luar Pulau  Tidak      SMA  Sudah  Karyawan  Terlambat
2       Perempuan  Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
3       Laki-laki      Luar Pulau     Ya       MA  Belum   Reguler  Terlambat
8       Perempuan  Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat
10      Laki-laki      Luar Pulau  Tidak      SMA  Sudah   Reguler  Terlambat
..            ...             ...    ...      ...    ...       ...        ...
135     Laki-laki  Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
137     Laki-laki  Dalam Provinsi     Ya      SMA  Sudah   Reguler  Terlambat
138     Perempuan  Dalam Provinsi     Ya      SMK  Sudah  Karyawan  Terlambat
140     Laki-laki      Luar Pulau     Ya       MA  Belum  Karyawan  Terlambat
141     Perempuan  Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat

[64 rows x 7 columns]

Memisahkan 70% data dari kelas yang bernilai "Terlambat" sebagai data training. 30% sisanya akan menjadi data testing.

In [8]:
# Menenentukan index ke berapa data akan dipotong
index_potong_terlambat = int(len(kelas_terlambat) * 0.71) #Ini hanya agar mendapat hasil 45
index_potong_terlambat

45

In [9]:
data_training_terlambat = kelas_terlambat.iloc[:index_potong_terlambat]
data_testing_terlambat = kelas_terlambat.iloc[index_potong_terlambat:]
print(len(data_training_terlambat))
print(len(data_testing_terlambat))
print(data_training_terlambat)
print()
print(data_testing_terlambat)

45
19
    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
0       Perempuan       Luar Pulau  Tidak      SMA  Sudah  Karyawan  Terlambat
2       Perempuan   Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
3       Laki-laki       Luar Pulau     Ya       MA  Belum   Reguler  Terlambat
8       Perempuan   Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat
10      Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler  Terlambat
11      Laki-laki  Dalam Kabupaten     Ya      SMA  Belum   Reguler  Terlambat
12      Laki-laki   Dalam Provinsi     Ya      SMA  Belum  Karyawan  Terlambat
14      Perempuan       Luar Pulau  Tidak      SMK  Sudah   Reguler  Terlambat
17      Laki-laki  Dalam Kabupaten     Ya       MA  Belum  Karyawan  Terlambat
18      Perempuan  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan  Terlambat
22      Perempuan       Luar Pulau  Tidak      SMA  Sudah   Reguler  Terlambat
23      Perempuan  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
26      Laki-laki  Dalam Kabupaten     Ya       MA  Sudah   Reguler  Terlambat
27      Perempuan       Luar Pulau  Tidak       MA  Sudah  Karyawan  Terlambat
30      Perempuan       Luar Pulau     Ya      SMK  Sudah  Karyawan  Terlambat
31      Laki-laki  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
36      Laki-laki       Luar Pulau     Ya      SMK  Sudah   Reguler  Terlambat
37      Perempuan  Dalam Kabupaten  Tidak      SMK  Sudah  Karyawan  Terlambat
42      Laki-laki   Dalam Provinsi     Ya      SMA  Belum  Karyawan  Terlambat
46      Laki-laki       Luar Pulau     Ya      SMA  Belum  Karyawan  Terlambat
49      Perempuan       Luar Pulau     Ya      SMA  Belum   Reguler  Terlambat
52      Perempuan       Luar Pulau     Ya      SMK  Belum   Reguler  Terlambat
53      Laki-laki       Luar Pulau     Ya      SMK  Sudah   Reguler  Terlambat
55      Perempuan       Luar Pulau     Ya      SMA  Sudah  Karyawan  Terlambat
63      Perempuan   Dalam Provinsi  Tidak      SMA  Sudah   Reguler  Terlambat
64      Laki-laki   Dalam Provinsi     Ya      SMK  Belum   Reguler  Terlambat
66      Laki-laki       Luar Pulau     Ya      SMA  Sudah  Karyawan  Terlambat
70      Laki-laki       Luar Pulau     Ya      SMK  Sudah  Karyawan  Terlambat
71      Laki-laki  Dalam Kabupaten     Ya      SMA  Sudah   Reguler  Terlambat
74      Perempuan  Dalam Kabupaten     Ya      SMK  Belum   Reguler  Terlambat
76      Laki-laki  Dalam Kabupaten     Ya      SMA  Belum   Reguler  Terlambat
81      Laki-laki  Dalam Kabupaten     Ya      SMA  Sudah  Karyawan  Terlambat
82      Laki-laki   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Terlambat
86      Perempuan  Dalam Kabupaten     Ya      SMA  Sudah  Karyawan  Terlambat
89      Laki-laki  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
90      Perempuan       Luar Pulau     Ya      SMA  Belum   Reguler  Terlambat
91      Perempuan   Dalam Provinsi  Tidak       MA  Sudah   Reguler  Terlambat
92      Laki-laki       Luar Pulau     Ya       MA  Sudah   Reguler  Terlambat
93      Laki-laki  Dalam Kabupaten     Ya       MA  Sudah   Reguler  Terlambat
95      Perempuan       Luar Pulau     Ya       MA  Belum   Reguler  Terlambat
98      Laki-laki   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
101     Laki-laki       Luar Pulau     Ya      SMK  Belum   Reguler  Terlambat
103     Perempuan       Luar Pulau     Ya      SMK  Sudah  Karyawan  Terlambat
105     Perempuan   Dalam Provinsi     Ya      SMK  Sudah   Reguler  Terlambat
107     Laki-laki   Dalam Provinsi     Ya      SMA  Belum  Karyawan  Terlambat

    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
108     Perempuan  Dalam Kabupaten     Ya       MA  Sudah   Reguler  Terlambat
110     Perempuan  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
112     Perempuan       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
114     Laki-laki       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
117     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
118     Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
119     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
123     Perempuan   Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
124     Laki-laki  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
125     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
127     Laki-laki       Luar Pulau     Ya       MA  Sudah  Karyawan  Terlambat
128     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
129     Perempuan   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Terlambat
133     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Terlambat
135     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
137     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah   Reguler  Terlambat
138     Perempuan   Dalam Provinsi     Ya      SMK  Sudah  Karyawan  Terlambat
140     Laki-laki       Luar Pulau     Ya       MA  Belum  Karyawan  Terlambat
141     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat

### Menggabungkan data training

In [10]:
join_training = pd.concat([data_training_tepat, data_training_terlambat])
data_training = join_training.sample(frac=1) #fungsi acak baris
print(len(data_training))
data_training

101

   JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
13     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler      Tepat
60     Laki-laki       Luar Pulau  Tidak       MA  Sudah  Karyawan      Tepat
52     Perempuan       Luar Pulau     Ya      SMK  Belum   Reguler  Terlambat
63     Perempuan   Dalam Provinsi  Tidak      SMA  Sudah   Reguler  Terlambat
25     Laki-laki       Luar Pulau     Ya      SMA  Belum   Reguler      Tepat
..           ...              ...    ...      ...    ...       ...        ...
75     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah   Reguler      Tepat
10     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler  Terlambat
57     Laki-laki       Luar Pulau  Tidak      SMK  Belum  Karyawan      Tepat
1      Laki-laki       Luar Pulau  Tidak      SMA  Belum  Karyawan      Tepat
73     Laki-laki       Luar Pulau  Tidak      SMA  Sudah  Karyawan      Tepat

[101 rows x 7 columns]

### Menggabungkan data testing

In [11]:
join_testing = pd.concat([data_testing_tepat,data_testing_terlambat])
data_testing = join_testing.sample(frac=1) #fungsi acak baris
print(len(data_testing))
data_testing

43

    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
124     Laki-laki  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
125     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
138     Perempuan   Dalam Provinsi     Ya      SMK  Sudah  Karyawan  Terlambat
116     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler      Tepat
120     Perempuan  Dalam Kabupaten  Tidak       MA  Belum   Reguler      Tepat
139     Perempuan   Dalam Provinsi     Ya      SMK  Belum  Karyawan      Tepat
119     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
137     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah   Reguler  Terlambat
117     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
133     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Terlambat
118     Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
96      Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler      Tepat
108     Perempuan  Dalam Kabupaten     Ya       MA  Sudah   Reguler  Terlambat
121     Perempuan       Luar Pulau  Tidak      SMA  Belum  Karyawan      Tepat
135     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
100     Perempuan       Luar Pulau     Ya      SMA  Belum  Karyawan      Tepat
111     Laki-laki       Luar Pulau     Ya      SMK  Belum   Reguler      Tepat
104     Perempuan       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
110     Perempuan  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
122     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler      Tepat
109     Perempuan       Luar Pulau  Tidak       MA  Belum  Karyawan      Tepat
99      Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan      Tepat
123     Perempuan   Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
143     Perempuan   Dalam Provinsi  Tidak       MA  Belum  Karyawan      Tepat
97      Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
142     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah  Karyawan      Tepat
115     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler      Tepat
128     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
132     Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan      Tepat
129     Perempuan   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Terlambat
106     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler      Tepat
127     Laki-laki       Luar Pulau     Ya       MA  Sudah  Karyawan  Terlambat
131     Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
112     Perempuan       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
114     Laki-laki       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
134     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler      Tepat
130     Laki-laki  Dalam Kabupaten  Tidak      SMA  Sudah  Karyawan      Tepat
102     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan      Tepat
136     Perempuan   Dalam Provinsi     Ya       MA  Belum   Reguler      Tepat
141     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat
126     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan      Tepat
113     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan      Tepat
140     Laki-laki       Luar Pulau     Ya       MA  Belum  Karyawan  Terlambat

# Hitung Probabilitas

##### Probabilitas kelas

In [12]:
print('Banyak data tepat : ', len(data_training_tepat))
print('Banyak data terlambat :', len(data_training_terlambat))
persen_tepat = len(data_training_tepat)/len(data_training)
persen_terlambat = len(data_training_terlambat)/len(data_training)

print(f"{persen_tepat:.2%}")
print(f"{persen_terlambat:.2%}")

Banyak data tepat :  56
Banyak data terlambat : 45
55.45%
44.55%

##### Kolom jenis kelamin

In [13]:
# Jumlah Tepat
jumlah_laki_tepat = len(data_training[(data_training['JENIS KELAMIN'] == 'Laki-laki') & (data_training['KELAS'] == 'Tepat')])
jumlah_perempuan_tepat = len(data_training[(data_training['JENIS KELAMIN'] == 'Perempuan') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_laki_terlambat = len(data_training[(data_training['JENIS KELAMIN'] == 'Laki-laki') & (data_training['KELAS'] == 'Terlambat')])
jumlah_perempuan_terlambat = len(data_training[(data_training['JENIS KELAMIN'] == 'Perempuan') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_laki_tepat = jumlah_laki_tepat/len(data_training_tepat)
persen_perempuan_tepat = jumlah_perempuan_tepat/len(data_training_tepat)
persen_laki_terlambat = jumlah_laki_terlambat/len(data_training_terlambat)
persen_perempuan_terlambat = jumlah_perempuan_terlambat/len(data_training_terlambat)

data = {
    'Jenis Kelamin': ['Laki-laki', 'Perempuan'],
    'Jumlah Tepat': [jumlah_laki_tepat, jumlah_perempuan_tepat],
    'Jumlah Terlambat': [jumlah_laki_terlambat, jumlah_perempuan_terlambat],
    'Persentase Tepat': [persen_laki_tepat, persen_perempuan_tepat],
    'Persentase Terlambat': [persen_laki_terlambat, persen_perempuan_terlambat]
}

df_jenisKelamin= pd.DataFrame(data)

# Menampilkan DataFrame
df_jenisKelamin

,Jenis Kelamin,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,Laki-laki,32,24,0.571429,0.533333
1,Perempuan,24,21,0.428571,0.466667

##### Kolom Asal Daerah

In [14]:
# Jumlah Tepat
jumlah_dk_tepat = len(data_training[(data_training['ASAL DAERAH'] == 'Dalam Kabupaten') & (data_training['KELAS'] == 'Tepat')]) # Dalam Kabupaten
jumlah_dp_tepat = len(data_training[(data_training['ASAL DAERAH'] == 'Dalam Provinsi') & (data_training['KELAS'] == 'Tepat')] )
jumlah_lp_tepat = len(data_training[(data_training['ASAL DAERAH'] == 'Luar Pulau') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_dk_terlambat = len(data_training[(data_training['ASAL DAERAH'] == 'Dalam Kabupaten') & (data_training['KELAS'] == 'Terlambat')])
jumlah_dp_terlambat = len(data_training[(data_training['ASAL DAERAH'] == 'Dalam Provinsi') & (data_training['KELAS'] == 'Terlambat')])
jumlah_lp_terlambat = len(data_training[(data_training['ASAL DAERAH'] == 'Luar Pulau') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_dk_tepat = jumlah_dk_tepat/len(data_training_tepat)
persen_dp_tepat = jumlah_dp_tepat/len(data_training_tepat)
persen_lp_tepat = jumlah_lp_tepat/len(data_training_tepat)
persen_dk_terlambat = jumlah_dk_terlambat/len(data_training_terlambat)
persen_dp_terlambat = jumlah_dp_terlambat/len(data_training_terlambat)
persen_lp_terlambat = jumlah_lp_terlambat/len(data_training_terlambat)

data_asal_daerah = {
    'Asal Daerah': ['Dalam Kabupaten', 'Dalam Provinsi', 'Luar Pulau'],
    'Jumlah Tepat': [jumlah_dk_tepat, jumlah_dp_tepat, jumlah_lp_tepat],
    'Jumlah Terlambat': [jumlah_dk_terlambat, jumlah_dp_terlambat, jumlah_lp_terlambat],
    'Persentase Tepat': [persen_dk_tepat, persen_dp_tepat, persen_lp_tepat],
    'Persentase Terlambat': [persen_dk_terlambat, persen_dp_terlambat, persen_lp_terlambat]
}

df_asalDaerah = pd.DataFrame(data_asal_daerah)

# Menampilkan DataFrame
df_asalDaerah

,Asal Daerah,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,Dalam Kabupaten,24,14,0.428571,0.311111
1,Dalam Provinsi,13,11,0.232143,0.244444
2,Luar Pulau,19,20,0.339286,0.444444

##### Kolom Cuti

In [15]:
# Jumlah Tepat
jumlah_cutiYa_tepat = len(data_training[(data_training['CUTI'] == 'Ya') & (data_training['KELAS'] == 'Tepat')])
jumlah_cutiTidak_tepat = len(data_training[(data_training['CUTI'] == 'Tidak') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_cutiYa_terlambat = len(data_training[(data_training['CUTI'] == 'Ya') & (data_training['KELAS'] == 'Terlambat')])
jumlah_cutiTidak_terlambat = len(data_training[(data_training['CUTI'] == 'Tidak') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_cutiYa_tepat = jumlah_cutiYa_tepat/len(data_training_tepat)
persen_cutiTidak_tepat = jumlah_cutiTidak_tepat/len(data_training_tepat)
persen_cutiYa_terlambat = jumlah_cutiYa_terlambat/len(data_training_terlambat)
persen_cutiTidak_terlambat = jumlah_cutiTidak_terlambat/len(data_training_terlambat)

data_cuti = {
    'CUTI': ['Ya', 'Tidak'],
    'Jumlah Tepat': [jumlah_cutiYa_tepat, jumlah_cutiTidak_tepat],
    'Jumlah Terlambat': [jumlah_cutiYa_terlambat, jumlah_cutiTidak_terlambat],
    'Persentase Tepat': [persen_cutiYa_tepat, persen_cutiTidak_tepat],
    'Persentase Terlambat': [persen_cutiYa_terlambat, persen_cutiTidak_terlambat]
}

df_cuti = pd.DataFrame(data_cuti)

# Menampilkan DataFrame
df_cuti

,CUTI,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,Ya,14,35,0.25,0.777778
1,Tidak,42,10,0.75,0.222222

##### Kolom Asal SMA

In [16]:
# Jumlah Tepat
jumlah_SMA_tepat = len(data_training[(data_training['ASAL SMA'] == 'SMA') & (data_training['KELAS'] == 'Tepat')])
jumlah_SMK_tepat = len(data_training[(data_training['ASAL SMA'] == 'SMK') & (data_training['KELAS'] == 'Tepat')])
jumlah_MA_tepat = len(data_training[(data_training['ASAL SMA'] == 'MA') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_SMA_terlambat = len(data_training[(data_training['ASAL SMA'] == 'SMA') & (data_training['KELAS'] == 'Terlambat')])
jumlah_SMK_terlambat = len(data_training[(data_training['ASAL SMA'] == 'SMK') & (data_training['KELAS'] == 'Terlambat')])
jumlah_MA_terlambat = len(data_training[(data_training['ASAL SMA'] == 'MA') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_SMA_tepat = jumlah_SMA_tepat/len(data_training_tepat)
persen_SMK_tepat = jumlah_SMK_tepat/len(data_training_tepat)
persen_MA_tepat = jumlah_MA_tepat/len(data_training_tepat)
persen_SMA_terlambat = jumlah_SMA_terlambat/len(data_training_terlambat)
persen_SMK_terlambat = jumlah_SMK_terlambat/len(data_training_terlambat)
persen_MA_terlambat = jumlah_MA_terlambat/len(data_training_terlambat)

# Buat DataFrame
data_asal_sma = {
    'ASAL SMA': ['SMA', 'SMK', 'MA'],
    'Jumlah Tepat': [jumlah_SMA_tepat, jumlah_SMK_tepat, jumlah_MA_tepat],
    'Jumlah Terlambat': [jumlah_SMA_terlambat, jumlah_SMK_terlambat, jumlah_MA_terlambat],
    'Persentase Tepat': [persen_SMA_tepat, persen_SMK_tepat, persen_MA_tepat],
    'Persentase Terlambat': [persen_SMA_terlambat, persen_SMK_terlambat, persen_MA_terlambat]
}

df_asal_sma = pd.DataFrame(data_asal_sma)

# Menampilkan DataFrame
df_asal_sma

,ASAL SMA,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,SMA,16,18,0.285714,0.400000
1,SMK,22,16,0.392857,0.355556
2,MA,18,11,0.321429,0.244444

##### Kolom Nikah

In [17]:
# Jumlah Tepat
jumlah_nikahYa_tepat = len(data_training[(data_training['NIKAH'] == 'Sudah') & (data_training['KELAS'] == 'Tepat')])
jumlah_nikahTidak_tepat = len(data_training[(data_training['NIKAH'] == 'Belum') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_nikahYa_terlambat = len(data_training[(data_training['NIKAH'] == 'Sudah') & (data_training['KELAS'] == 'Terlambat')])
jumlah_nikahTidak_terlambat = len(data_training[(data_training['NIKAH'] == 'Belum') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_nikahYa_tepat = jumlah_nikahYa_tepat/len(data_training_tepat)
persen_nikahTidak_tepat = jumlah_nikahTidak_tepat/len(data_training_tepat)
persen_nikahYa_terlambat = jumlah_nikahYa_terlambat/len(data_training_terlambat)
persen_nikahTidak_terlambat = jumlah_nikahTidak_terlambat/len(data_training_terlambat)

# Buat DataFrame
data_nikah = {
    'NIKAH': ['Sudah', 'Belum'],
    'Jumlah Tepat': [jumlah_nikahYa_tepat, jumlah_nikahTidak_tepat],
    'Jumlah Terlambat': [jumlah_nikahYa_terlambat, jumlah_nikahTidak_terlambat],
    'Persentase Tepat': [persen_nikahYa_tepat, persen_nikahTidak_tepat],
    'Persentase Terlambat': [persen_nikahYa_terlambat, persen_nikahTidak_terlambat]
}

df_nikah = pd.DataFrame(data_nikah)

# Menampilkan DataFrame
df_nikah

,NIKAH,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,Sudah,20,30,0.357143,0.666667
1,Belum,36,15,0.642857,0.333333

##### Kolom Program

In [21]:
# Jumlah Tepat
jumlah_karyawan_tepat = len(data_training[(data_training['PROGRAM'] == 'Karyawan') & (data_training['KELAS'] == 'Tepat')])
jumlah_reguler_tepat = len(data_training[(data_training['PROGRAM'] == 'Reguler') & (data_training['KELAS'] == 'Tepat')])

# Jumlah Terlambat
jumlah_karyawan_terlambat = len(data_training[(data_training['PROGRAM'] == 'Karyawan') & (data_training['KELAS'] == 'Terlambat')])
jumlah_reguler_terlambat = len(data_training[(data_training['PROGRAM'] == 'Reguler') & (data_training['KELAS'] == 'Terlambat')])

# Probabilitas
persen_karyawan_tepat = jumlah_karyawan_tepat/len(data_training_tepat)
persen_reguler_tepat = jumlah_reguler_tepat/len(data_training_tepat)
persen_karyawan_terlambat = jumlah_karyawan_terlambat/len(data_training_terlambat)
persen_reguler_terlambat = jumlah_reguler_terlambat/len(data_training_terlambat)

# Buat DataFrame
data_program = {
    'PROGRAM': ['Karyawan', 'Reguler'],
    'Jumlah Tepat': [jumlah_karyawan_tepat, jumlah_reguler_tepat],
    'Jumlah Terlambat': [jumlah_karyawan_terlambat, jumlah_reguler_terlambat],
    'Persentase Tepat': [persen_karyawan_tepat, persen_reguler_tepat],
    'Persentase Terlambat': [persen_karyawan_terlambat, persen_reguler_terlambat]
}

df_program = pd.DataFrame(data_program)

# Menampilkan DataFrame
df_program

,PROGRAM,Jumlah Tepat,Jumlah Terlambat,Persentase Tepat,Persentase Terlambat
0,Karyawan,27,22,0.482143,0.488889
1,Reguler,29,23,0.517857,0.511111

# Prediksi
Memprediksi nilai pada kolom kelas di data testing

In [24]:
# Prediksi nilai 
data_testing_copy = data_testing.copy()
data_testing_copy

    JENIS KELAMIN      ASAL DAERAH   CUTI ASAL SMA  NIKAH   PROGRAM      KELAS
124     Laki-laki  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
125     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
138     Perempuan   Dalam Provinsi     Ya      SMK  Sudah  Karyawan  Terlambat
116     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler      Tepat
120     Perempuan  Dalam Kabupaten  Tidak       MA  Belum   Reguler      Tepat
139     Perempuan   Dalam Provinsi     Ya      SMK  Belum  Karyawan      Tepat
119     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
137     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah   Reguler  Terlambat
117     Perempuan   Dalam Provinsi     Ya       MA  Sudah   Reguler  Terlambat
133     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan  Terlambat
118     Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
96      Laki-laki   Dalam Provinsi  Tidak      SMK  Sudah   Reguler      Tepat
108     Perempuan  Dalam Kabupaten     Ya       MA  Sudah   Reguler  Terlambat
121     Perempuan       Luar Pulau  Tidak      SMA  Belum  Karyawan      Tepat
135     Laki-laki   Dalam Provinsi     Ya       MA  Belum   Reguler  Terlambat
100     Perempuan       Luar Pulau     Ya      SMA  Belum  Karyawan      Tepat
111     Laki-laki       Luar Pulau     Ya      SMK  Belum   Reguler      Tepat
104     Perempuan       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
110     Perempuan  Dalam Kabupaten     Ya      SMK  Sudah  Karyawan  Terlambat
122     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler      Tepat
109     Perempuan       Luar Pulau  Tidak       MA  Belum  Karyawan      Tepat
99      Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan      Tepat
123     Perempuan   Dalam Provinsi     Ya       MA  Sudah  Karyawan  Terlambat
143     Perempuan   Dalam Provinsi  Tidak       MA  Belum  Karyawan      Tepat
97      Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
142     Laki-laki   Dalam Provinsi     Ya      SMA  Sudah  Karyawan      Tepat
115     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler      Tepat
128     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah   Reguler  Terlambat
132     Perempuan       Luar Pulau  Tidak      SMK  Belum  Karyawan      Tepat
129     Perempuan   Dalam Provinsi     Ya      SMA  Sudah  Karyawan  Terlambat
106     Perempuan   Dalam Provinsi  Tidak      SMA  Belum   Reguler      Tepat
127     Laki-laki       Luar Pulau     Ya       MA  Sudah  Karyawan  Terlambat
131     Laki-laki       Luar Pulau  Tidak      SMA  Belum   Reguler      Tepat
112     Perempuan       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
114     Laki-laki       Luar Pulau  Tidak       MA  Belum   Reguler  Terlambat
134     Laki-laki       Luar Pulau  Tidak      SMA  Sudah   Reguler      Tepat
130     Laki-laki  Dalam Kabupaten  Tidak      SMA  Sudah  Karyawan      Tepat
102     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan      Tepat
136     Perempuan   Dalam Provinsi     Ya       MA  Belum   Reguler      Tepat
141     Perempuan   Dalam Provinsi  Tidak      SMK  Sudah  Karyawan  Terlambat
126     Laki-laki  Dalam Kabupaten  Tidak       MA  Sudah  Karyawan      Tepat
113     Laki-laki  Dalam Kabupaten     Ya      SMK  Belum  Karyawan      Tepat
140     Laki-laki       Luar Pulau     Ya       MA  Belum  Karyawan  Terlambat

## Fungsi Naive Bayes

In [22]:
def naive_bayes_prediction(jenisKelamin, asalDaerah, cuti, asalSMA ,nikah, program ):
    persentase_jenisKelamin = {'Laki-laki': {'Tepat': persen_laki_tepat, 'Terlambat': persen_terlambat},
                            'Perempuan': {'Tepat': persen_perempuan_tepat, 'Terlambat': persen_perempuan_terlambat}}

    persentase_asalDaerah = {'Dalam Kabupaten': {'Tepat': persen_dk_tepat, 'Terlambat': persen_dk_terlambat},
                            'Dalam Provinsi': {'Tepat': persen_dp_tepat, 'Terlambat': persen_dp_terlambat},
                                'Luar Pulau': {'Tepat': persen_lp_tepat, 'Terlambat': persen_lp_terlambat}}
    
    persentase_cuti = {'Ya': {'Tepat': persen_cutiYa_tepat, 'Terlambat': persen_cutiYa_terlambat},
                            'Tidak': {'Tepat': persen_cutiTidak_tepat, 'Terlambat': persen_cutiTidak_terlambat}}
    
    persentase_asalSMA = {'SMA': {'Tepat': persen_SMA_tepat, 'Terlambat': persen_SMA_terlambat},
                            'SMK': {'Tepat': persen_SMK_tepat, 'Terlambat': persen_SMK_terlambat},
                                'MA': {'Tepat': persen_MA_tepat, 'Terlambat': persen_MA_terlambat}}
    
    persentase_nikah = {'Sudah': {'Tepat': persen_nikahYa_tepat, 'Terlambat': persen_nikahYa_terlambat},
                            'Belum': {'Tepat': persen_nikahTidak_tepat, 'Terlambat': persen_nikahTidak_terlambat}}
    
    persentase_golongan = {'Karyawan': {'Tepat': persen_karyawan_tepat, 'Terlambat': persen_karyawan_terlambat},
                            'Reguler': {'Tepat': persen_reguler_tepat, 'Terlambat': persen_reguler_terlambat}}
    
    # Menghitung prediksi untuk kelas 'Tepat'
    prediksi_tepat = (
        persen_tepat *
        persentase_jenisKelamin.get(jenisKelamin, 0).get('Tepat', 0) *
        persentase_asalDaerah.get(asalDaerah, 0).get('Tepat', 0) *
        persentase_cuti.get(cuti, 0).get('Tepat', 0) *
        persentase_asalSMA.get(asalSMA, 0).get('Tepat', 0) *
        persentase_nikah.get(nikah, 0).get('Tepat', 0) *
        persentase_golongan.get(program, 0).get('Tepat', 0)
    )

    # Menghitung prediksi untuk kelas 'Terlambat'
    prediksi_terlambat = (
        persen_terlambat *
        persentase_jenisKelamin.get(jenisKelamin, 0).get('Terlambat', 0) *
        persentase_asalDaerah.get(asalDaerah, 0).get('Terlambat', 0) *
        persentase_cuti.get(cuti, 0).get('Terlambat', 0) *
        persentase_asalSMA.get(asalSMA, 0).get('Terlambat', 0) *
        persentase_nikah.get(nikah, 0).get('Terlambat', 0) *
        persentase_golongan.get(program, 0).get('Terlambat', 0)
    )

    print(f'Persentase tepat: {prediksi_tepat}')
    print(f'Persentase terlambat: {prediksi_terlambat}')

    prediksi = max(prediksi_tepat, prediksi_terlambat)
    if prediksi == prediksi_tepat:
        return 'Tepat'
    else:
        return 'Terlambat'
    

    
jenisKelamin = input('Masukkan jenis kelamin anda? (Laki-laki/Perempuan): ')
asalDaerah = input('Dari mana asal anda? (Dalam Kabupaten/Dalam Provinsi/Luar Pulau: ')
cuti = input('Pernahkah anda cuti? (Ya/Tidak): ')
asalSMA = input('Masukkan asal SMA anda (SMA/SMK/MA): ')
nikah = input('Sudahkah anda menikah? (Sudah/Belum): ')
program = input('Program yang anda ikuti (Karyawan/Reguler): ')



kelas_prediksi = naive_bayes_prediction(jenisKelamin, asalDaerah, cuti, asalSMA, nikah, program)
print("Prediksi Kelas: ", kelas_prediksi)

Persentase tepat: 0.002296382282959658
Persentase terlambat: 0.005566467904582904
Prediksi Kelas:  Terlambat